package sistema;

public enum Genero {
    AÇÃO_E_AVENTURA, ARTE_E_FOTOGRAFIA, AUTOAJUDA, BIOGRAFIA, CONTO, CRIMES_REAIS, DISTOPIA, ENSAIOS, FANTASIA, FICÇÃO_CIENTÍFICA, 
    FICÇÃO_CONTEMPORÂNEA, FICÇÃO_FEMININA, FICÇÃO_HISTÓRICA, FICÇÃO_POLICIAL, GASTRONOMIA, GRAPHIC_NOVEL, GUIAS_E_COMO_FAZER, HISTÓRIA, 
    HORROR, HUMANIDADES_E_CIÊNCIAS_SOCIAIS, HUMOR, INFANTIL, LGBTQ_PLUS, MEMÓRIAS_E_AUTOBIOGRAFIA, NEW_ADULT, NOVELA, OUTRO, PATERNIDADE_E_FAMÍLIA,
    REALISMO_MÁGICO, RELIGIÃO_E_ESPIRITUALIDADE, ROMANCE, TECHONOLOGIA_E_CIÊNCIA, THRILLER_E_SUSPENSE, VIAGEM, VAZIO, YOUNG_ADULT
}
